-- AUTO-GENERATED by generate_exports.sh — do not edit
-- Re-exports only _test names needed by the header.
import DeanLean.Cpp.Tests.Ordering

export Cpp (strongCmp_refl_nat_test strongCmp_flip_nat_test strongCmp_lt_trans_nat_test strongCmp_refl_int_test strongCmp_flip_int_test strongCmp_refl_pair_test strongCmp_flip_pair_test strongCmp_lt_trans_pair_test flip_involution_test toWeak_preserves_test toPartial_preserves_test )
