-- AUTO-GENERATED by generate_exports.sh — do not edit
-- Re-exports only _test names needed by the header.
import DeanLean.Cpp.Tests.Variant

export Cpp.Variant2 (index_determines_alternative_test exactly_one_alternative_test different_constructors_different_index_test visit_determines_equality_test index_determines_alternative_test exactly_one_alternative_test )
