#!/bin/bash
# Generate Proofs/*.exports.lean and Tests/*.exports.lean from headers.
# These files re-export ONLY the _proof and _test names that headers need.
# Headers import the exports file, not the raw Proofs/Tests files.
# This prevents definitions from leaking out of Proofs/Tests into headers.

set -e

HEADER_DIR="DeanLean/Cpp"
PROOFS_DIR="DeanLean/Cpp/Proofs"
TESTS_DIR="DeanLean/Cpp/Tests"

for header in "$HEADER_DIR"/*.lean; do
    module=$(basename "$header" .lean)

    # Skip if no corresponding Proofs file
    [ -f "$PROOFS_DIR/$module.lean" ] || continue

    # Extract namespace from header (first 'namespace' line)
    ns=$(grep "^namespace " "$header" | head -1 | sed 's/namespace //')
    [ -z "$ns" ] && continue

    # Collect _proof names from ProvenTheorem declarations
    proof_names=$(grep "^ProvenTheorem " "$header" | sed 's/ProvenTheorem \([^ ]*\) .*/\1_proof/')

    # Collect _test names from TestedConjecture declarations
    test_names=$(grep "^TestedConjecture " "$header" | sed 's/TestedConjecture \([^ ]*\) .*/\1_test/')

    # Generate Proofs exports file
    if [ -n "$proof_names" ]; then
        exports_file="$PROOFS_DIR/${module}.exports.lean"
        echo "-- AUTO-GENERATED by generate_exports.sh — do not edit" > "$exports_file"
        echo "-- Re-exports only _proof names needed by the header." >> "$exports_file"
        echo "import DeanLean.Cpp.Proofs.$module" >> "$exports_file"
        echo "" >> "$exports_file"
        echo -n "export $ns (" >> "$exports_file"
        echo "$proof_names" | tr '\n' ' ' >> "$exports_file"
        echo ")" >> "$exports_file"
        echo "  Generated $exports_file"
    fi

    # Generate Tests exports file
    if [ -n "$test_names" ]; then
        exports_file="$TESTS_DIR/${module}.exports.lean"
        echo "-- AUTO-GENERATED by generate_exports.sh — do not edit" > "$exports_file"
        echo "-- Re-exports only _test names needed by the header." >> "$exports_file"
        echo "import DeanLean.Cpp.Tests.$module" >> "$exports_file"
        echo "" >> "$exports_file"
        echo -n "export $ns (" >> "$exports_file"
        echo "$test_names" | tr '\n' ' ' >> "$exports_file"
        echo ")" >> "$exports_file"
        echo "  Generated $exports_file"
    fi
done

echo "Done."
