import Lean
import DeanLean.Attr
/-! # DeanLean/IndexGen.lean — Reusable theorem index generator

Generic utility for any project using lean-manifests. Walks the environment,
cross-references @[theorems] annotations with auto-detected mentions in
theorem statements, and emits a markdown index.

Usage from a caller project:

```lean
import DeanLean.IndexGen

def main : IO Unit := do
  DeanLean.IndexGen.run "L3m" "docs/theorem-index.md" #[{ module := `L3m }]
```
-/

namespace DeanLean.IndexGen

open Lean

/-- Classify a theorem by its evidence level. -/
def classifyTheorem (env : Environment) (name : Name) : String :=
  if hasManifestAxiomAttr env name then "ManifestAxiom"
  else if hasManifestEntryAttr env name then
    match env.find? name with
    | some (.thmInfo val) =>
      if val.value.hasSorry then "TestedConjecture"
      else "ProvenTheorem"
    | some (.axiomInfo _) => "ProvenTheorem"
    | _ => "theorem"
  else "theorem"

/-- Collect all constants with a given prefix mentioned in an Expr. -/
partial def collectPrefixedConstants (prefix_ : String) (e : Expr) : Std.HashSet Name := Id.run do
  let mut result : Std.HashSet Name := {}
  let mut stack : List Expr := [e]
  while h : !stack.isEmpty do
    let expr := stack.head (by simp_all)
    stack := stack.tail
    match expr with
    | .const name _ =>
      if name.toString.startsWith prefix_ then
        result := result.insert name
    | .app f a => stack := f :: a :: stack
    | .lam _ t b _ => stack := t :: b :: stack
    | .forallE _ t b _ => stack := t :: b :: stack
    | .letE _ t v b _ => stack := t :: v :: b :: stack
    | .mdata _ e => stack := e :: stack
    | .proj _ _ e => stack := e :: stack
    | _ => pure ()
  return result

/-- Entry for a function in the index. -/
structure FunctionEntry where
  name : Name
  modPath : String
  annotatedTheorems : Array Name
  autoDetectedTheorems : Array (Name × String)
  deriving Inhabited

/-- Generate a theorem index for all constants with the given namespace prefix. -/
def generateIndex (env : Environment) (namespacePrefix : String) : Array FunctionEntry := Id.run do
  let prefix_ := namespacePrefix ++ "."

  -- Step 1: Collect annotated functions
  let mut annotatedMap : Std.HashMap Name (Array Name) := {}
  for (name, _) in env.constants.map₁.toList do
    if let some thms := getTheorems? env name then
      annotatedMap := annotatedMap.insert name thms

  -- Step 2: Walk all manifest-entry theorems, find prefixed constants in types
  let mut autoMap : Std.HashMap Name (Array (Name × String)) := {}
  for (name, ci) in env.constants.map₁.toList do
    if !name.toString.startsWith prefix_ then continue
    let isManifest := hasManifestEntryAttr env name || hasManifestAxiomAttr env name
    if !isManifest then continue
    let isThm := match ci with
      | .thmInfo _ => true
      | .axiomInfo _ => true
      | _ => false
    if !isThm then continue
    let kind := classifyTheorem env name
    let mentioned := collectPrefixedConstants prefix_ ci.type
    for fn in mentioned do
      if fn == name then continue
      match env.find? fn with
      | some (.defnInfo _) | some (.opaqueInfo _) =>
        let prev := autoMap.getD fn #[]
        if !prev.any (·.1 == name) then
          autoMap := autoMap.insert fn (prev.push (name, kind))
      | _ => pure ()

  -- Step 3: Merge
  let mut allFunctions : Std.HashSet Name := {}
  for (fn, _) in annotatedMap.toArray do allFunctions := allFunctions.insert fn
  for (fn, _) in autoMap.toArray do allFunctions := allFunctions.insert fn

  let mut entries : Array FunctionEntry := #[]
  for fn in allFunctions do
    let modOpt := env.getModuleIdxFor? fn
    let modStr := match modOpt with
      | some idx =>
        let m := env.allImportedModuleNames.get! idx
        m.toString.replace "." "/" ++ ".lean"
      | none => "unknown"
    let annotated := annotatedMap.getD fn #[]
    let auto := autoMap.getD fn #[]
    entries := entries.push { name := fn, modPath := modStr, annotatedTheorems := annotated, autoDetectedTheorems := auto }

  entries.qsort (fun a b => a.name.toString < b.name.toString)

/-- Render the index as markdown. -/
def renderMarkdown (env : Environment) (entries : Array FunctionEntry) : String := Id.run do
  let mut out := "# Theorem Index\n\n"
  out := out ++ "*Auto-generated by DeanLean.IndexGen. Do not edit.*\n\n"
  let totalAnnotated := entries.foldl (fun acc e => acc + e.annotatedTheorems.size) 0
  let totalAuto := entries.foldl (fun acc e => acc + e.autoDetectedTheorems.size) 0
  out := out ++ s!"**{entries.size} functions indexed, {totalAnnotated} annotated links, {totalAuto} auto-detected links.**\n\n"

  for entry in entries do
    out := out ++ s!"## `{entry.name}` ({entry.modPath})\n\n"
    if entry.annotatedTheorems.size > 0 then
      out := out ++ "  **Annotated:**\n"
      for thm in entry.annotatedTheorems do
        let kind := classifyTheorem env thm
        out := out ++ s!"  - `{thm}` [{kind}]\n"
      out := out ++ "\n"
    let autoOnly := entry.autoDetectedTheorems.filter (fun (t, _) => !entry.annotatedTheorems.contains t)
    if autoOnly.size > 0 then
      out := out ++ "  **Auto-detected (mentions in theorem statements):**\n"
      for (thm, kind) in autoOnly do
        out := out ++ s!"  - `{thm}` [{kind}]\n"
      out := out ++ "\n"
    let bothItems := entry.autoDetectedTheorems.filter (fun (t, _) => entry.annotatedTheorems.contains t)
    if bothItems.size > 0 then
      out := out ++ "  **Both (annotated + auto-detected):**\n"
      for (thm, kind) in bothItems do
        out := out ++ s!"  - `{thm}` [{kind}]\n"
      out := out ++ "\n"
  return out

/-- Look up theorems for a single function. Returns formatted string. -/
def lookupFunction (env : Environment) (namespacePrefix : String) (target : Name) : String := Id.run do
  let prefix_ := namespacePrefix ++ "."
  let modOpt := env.getModuleIdxFor? target
  let modStr := match modOpt with
    | some idx => (env.allImportedModuleNames.get! idx).toString.replace "." "/" ++ ".lean"
    | none => "unknown"

  let mut out := s!"## {target} ({modStr})\n\n"

  match getTheorems? env target with
  | some thms =>
    out := out ++ "  Annotated:\n"
    for thm in thms do
      out := out ++ s!"    - {thm}\n"
  | none => pure ()

  let mut autoFound : Array (Name × String) := #[]
  for (name, ci) in env.constants.map₁.toList do
    if !name.toString.startsWith prefix_ then continue
    let isManifest := hasManifestEntryAttr env name || hasManifestAxiomAttr env name
    if !isManifest then continue
    let isThm := match ci with
      | .thmInfo _ => true
      | .axiomInfo _ => true
      | _ => false
    if !isThm then continue
    let mentioned := collectPrefixedConstants prefix_ ci.type
    if mentioned.contains target then
      autoFound := autoFound.push (name, classifyTheorem env name)

  if autoFound.size > 0 then
    let sortedAuto := autoFound.qsort (fun a b => a.1.toString < b.1.toString)
    out := out ++ "  Auto-detected (mentions in theorem statements):\n"
    for (thm, kind) in sortedAuto do
      out := out ++ s!"    - {thm}  [{kind}]\n"

  if autoFound.isEmpty then
    match getTheorems? env target with
    | some _ => pure ()
    | none => out := out ++ "  (no theorems found for this function)\n"
  return out

/-- Main entry point: generate index and write to file. -/
def run (namespacePrefix : String) (outputFile : System.FilePath)
    (imports : Array Lean.Import) : IO Unit := do
  let env ← importModules imports {} 0
  let entries := generateIndex env namespacePrefix
  let md := renderMarkdown env entries
  IO.FS.writeFile outputFile md
  let totalAnnotated := entries.foldl (fun acc e => acc + e.annotatedTheorems.size) 0
  let totalAuto := entries.foldl (fun acc e => acc + e.autoDetectedTheorems.size) 0
  IO.println s!"✓ Generated {outputFile} ({entries.size} functions, {totalAnnotated} annotated, {totalAuto} auto-detected)"

end DeanLean.IndexGen
