-- AUTO-GENERATED by generate_exports.sh — do not edit
-- Re-exports only _proof names needed by the header.
import DeanLean.Cpp.Proofs.Algorithm

export Cpp (cppMin_cases_proof cppMin_le_left_proof cppMin_le_right_proof cppMin_self_proof cppMin_comm_proof cppMax_cases_proof cppMax_ge_left_proof cppMax_ge_right_proof cppMax_self_proof cppMax_comm_proof cppClamp_trichotomy_proof cppClamp_in_range_proof cppClamp_lo_proof cppClamp_hi_proof isSorted_nil_proof isSorted_singleton_proof isSorted_cons_proof isSorted_tail_proof minElement_mem_proof minElement_le_proof )
