-- AUTO-GENERATED by generate_exports.sh — do not edit
-- Re-exports only _proof names needed by the header.
import DeanLean.Cpp.Proofs.Concepts

export Cpp.Concepts (same_as_symmetric_proof same_as_refl_proof )
