-- AUTO-GENERATED by generate_exports.sh — do not edit
-- Re-exports only _proof names needed by the header.
import DeanLean.Cpp.Proofs.Pair

export Cpp.Pair (swap_swap_proof swap_first_proof swap_second_proof make_first_proof make_second_proof eq_iff_components_proof map_first_id_proof map_second_id_proof tuple_size_is_2_proof )
