-- AUTO-GENERATED by generate_exports.sh — do not edit
-- Re-exports only _proof names needed by the header.
import DeanLean.Cpp.Proofs.Sort

export Cpp.Sort (insertionSort_sorted_proof insertionSort_perm_proof insertionSort_length_proof isSorted_iff_IsSorted_proof )
